-- Feature switches (Admin Settings) + login failure reason + audit action

CREATE TABLE `SystemFeatureSettings` (
  `id` VARCHAR(191) NOT NULL,
  `studentLoginEnabled` BOOLEAN NOT NULL DEFAULT true,
  `updatedByUserId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `SystemFeatureSettings` (`id`, `studentLoginEnabled`, `updatedAt`)
VALUES ('default', true, CURRENT_TIMESTAMP(3));

ALTER TABLE `SystemFeatureSettings`
  ADD CONSTRAINT `SystemFeatureSettings_updatedByUserId_fkey`
  FOREIGN KEY (`updatedByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `LoginLog`
  MODIFY `failureReason` ENUM('INVALID_CREDENTIALS', 'INACTIVE', 'FEATURE_DISABLED') NULL;

ALTER TABLE `UserAuditLog` MODIFY `action` ENUM(
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DEACTIVATED',
  'PASSWORD_RESET_REQUESTED',
  'PASSWORD_RESET_COMPLETED',
  'PASSWORD_FORCE_SET_BY_ADMIN',
  'STUDENT_IMPORTED',
  'TEACHER_IMPORTED',
  'STUDENT_PROMOTED',
  'STUDENT_ARCHIVED',
  'STUDENT_REACTIVATED',
  'STUDENT_DELETED',
  'BACKUP_SETTINGS_UPDATED',
  'BACKUP_MANUAL_STARTED',
  'BACKUP_MANUAL_SUCCESS',
  'BACKUP_MANUAL_FAILED',
  'BACKUP_FILE_DOWNLOADED',
  'BACKUP_FILE_DELETED',
  'FEATURE_SETTINGS_UPDATED'
) NOT NULL;
