-- Offline / alternative-channel payment marking for cash-in (and fee audit trail)

ALTER TABLE `FeeAuditLog`
  MODIFY COLUMN `action` ENUM(
    'FEE_RULE_CREATED',
    'FEE_RULE_UPDATED',
    'EXCHANGE_RATE_UPDATED',
    'FEE_STATEMENT_GENERATED',
    'FEE_STATEMENT_BATCH_GENERATED',
    'FEE_STATEMENT_PRINTED',
    'FEE_SUMMARY_EXPORTED',
    'FEE_DETAILS_EXPORTED',
    'FEE_SCHEDULE_VERSION_CREATED',
    'REGISTRATION_FEE_STATEMENT_GENERATED',
    'POST_RESULTS_FEE_STATEMENT_GENERATED',
    'FEE_STATEMENT_MARKED_NEEDS_REGENERATION',
    'FEE_STATEMENT_REGENERATED_REVISED',
    'FEE_STATEMENT_ISSUED',
    'EXAM_ADDED',
    'EXAM_REMOVED',
    'EXAM_REPLACED',
    'CANDIDATE_REGISTRATION_FEE_ADDED',
    'CANDIDATE_REGISTRATION_FEE_REMOVED',
    'ADDITIONAL_SERVICE_ADDED',
    'ADDITIONAL_SERVICE_REMOVED',
    'OFFLINE_WITHDRAWAL_REFUND_RECORDED',
    'OFFLINE_WITHDRAWAL_REFUND_COMPLETED',
    'FEE_STATEMENT_MARKED_PAID_OFFLINE'
  ) NOT NULL;

ALTER TABLE `PostResultsAuditLog`
  MODIFY `action` ENUM(
    'REVIEW_WINDOW_CREATED',
    'REVIEW_WINDOW_UPDATED',
    'REVIEW_WINDOW_LOCKED',
    'REVIEW_SERVICE_ENABLED',
    'REVIEW_SERVICE_DISABLED',
    'REVIEW_REQUEST_CREATED',
    'REVIEW_REQUEST_UPDATED',
    'REVIEW_REQUEST_SUBMITTED',
    'CASH_IN_REQUEST_CREATED',
    'CASH_IN_REQUEST_UPDATED',
    'ACCESS_TO_SCRIPT_REQUEST_CREATED',
    'CERTIFICATE_REQUEST_CREATED',
    'FEE_SCHEDULE_VERSION_CREATED',
    'REGISTRATION_FEE_STATEMENT_GENERATED',
    'POST_RESULTS_FEE_STATEMENT_GENERATED',
    'CASH_IN_FEE_MARKED_PAID_OFFLINE'
  ) NOT NULL;
