-- Finance staff role. Same enum is stored on several columns.

ALTER TABLE `User`
  MODIFY COLUMN `role` ENUM('ADMIN', 'EXAM_OFFICER', 'SUBJECT_TEACHER', 'STUDENT', 'FINANCE') NOT NULL DEFAULT 'STUDENT';

ALTER TABLE `LoginLog`
  MODIFY COLUMN `roleSnapshot` ENUM('ADMIN', 'EXAM_OFFICER', 'SUBJECT_TEACHER', 'STUDENT', 'FINANCE') NULL;

ALTER TABLE `RegistrationWorkspace`
  MODIFY COLUMN `lastAdjustedByRole` ENUM('ADMIN', 'EXAM_OFFICER', 'SUBJECT_TEACHER', 'STUDENT', 'FINANCE') NULL;

ALTER TABLE `StudentExamRegistration`
  MODIFY COLUMN `addedByRole` ENUM('ADMIN', 'EXAM_OFFICER', 'SUBJECT_TEACHER', 'STUDENT', 'FINANCE') NULL;

ALTER TABLE `RegistrationAuditLog`
  MODIFY COLUMN `performedByRole` ENUM('ADMIN', 'EXAM_OFFICER', 'SUBJECT_TEACHER', 'STUDENT', 'FINANCE') NULL;

ALTER TABLE `RegistrationChangeRequest`
  MODIFY COLUMN `requestedByRole` ENUM('ADMIN', 'EXAM_OFFICER', 'SUBJECT_TEACHER', 'STUDENT', 'FINANCE') NOT NULL;
