-- Restore MANUAL on markup enums (removed by post_results_domain migration).
-- Fee rules use markupType=MANUAL; generating statements failed with:
-- Data truncated for column 'markupTypeSnapshot'

ALTER TABLE `FeeStatementItem`
  MODIFY `markupTypeSnapshot` ENUM('PERCENTAGE', 'FIXED_AMOUNT', 'MANUAL') NULL;

ALTER TABLE `FeeSchedule`
  MODIFY `markupType` ENUM('PERCENTAGE', 'FIXED_AMOUNT', 'MANUAL') NULL;

-- Audit action for explicit reprice-by-current-fee-stage
ALTER TABLE `FeeAuditLog`
  MODIFY COLUMN `action` ENUM(
    'FEE_RULE_CREATED',
    'FEE_RULE_UPDATED',
    'EXCHANGE_RATE_UPDATED',
    'FEE_STATEMENT_GENERATED',
    'FEE_STATEMENT_BATCH_GENERATED',
    'FEE_STATEMENT_PRINTED',
    'FEE_SUMMARY_EXPORTED',
    'FEE_DETAILS_EXPORTED',
    'FEE_SCHEDULE_VERSION_CREATED',
    'REGISTRATION_FEE_STATEMENT_GENERATED',
    'POST_RESULTS_FEE_STATEMENT_GENERATED',
    'FEE_STATEMENT_MARKED_NEEDS_REGENERATION',
    'FEE_STATEMENT_REGENERATED_REVISED',
    'FEE_STATEMENT_ISSUED',
    'EXAM_ADDED',
    'EXAM_REMOVED',
    'EXAM_REPLACED',
    'CANDIDATE_REGISTRATION_FEE_ADDED',
    'CANDIDATE_REGISTRATION_FEE_REMOVED',
    'ADDITIONAL_SERVICE_ADDED',
    'ADDITIONAL_SERVICE_REMOVED',
    'OFFLINE_WITHDRAWAL_REFUND_RECORDED',
    'OFFLINE_WITHDRAWAL_REFUND_COMPLETED',
    'FEE_STATEMENT_MARKED_PAID_OFFLINE',
    'FEE_STATEMENT_REPRICED_BY_CURRENT_STAGE'
  ) NOT NULL;
