-- Registration type and billing scope refinement

ALTER TABLE `RegistrationWorkspace`
  ADD COLUMN `registrationNumber` VARCHAR(191) NULL;

CREATE UNIQUE INDEX `RegistrationWorkspace_registrationNumber_key` ON `RegistrationWorkspace`(`registrationNumber`);

ALTER TABLE `FeeStatement`
  ADD COLUMN `studentVisible` BOOLEAN NOT NULL DEFAULT true;

-- RegistrationType enum migration
ALTER TABLE `RegistrationWorkspace` MODIFY `registrationType` ENUM('NORMAL', 'RESTRICTED', 'EXTERNAL', 'INTERNAL_NORMAL', 'RESTRICTED_INTERNAL') NOT NULL DEFAULT 'NORMAL';
ALTER TABLE `StudentExamRegistration` MODIFY `registrationType` ENUM('NORMAL', 'RESTRICTED', 'EXTERNAL', 'INTERNAL_NORMAL', 'RESTRICTED_INTERNAL') NOT NULL DEFAULT 'NORMAL';

UPDATE `RegistrationWorkspace` SET `registrationType` = 'INTERNAL_NORMAL' WHERE `registrationType` = 'NORMAL';
UPDATE `StudentExamRegistration` SET `registrationType` = 'INTERNAL_NORMAL' WHERE `registrationType` = 'NORMAL';
UPDATE `RegistrationWorkspace` SET `registrationType` = 'RESTRICTED_INTERNAL' WHERE `registrationType` = 'RESTRICTED';
UPDATE `StudentExamRegistration` SET `registrationType` = 'RESTRICTED_INTERNAL' WHERE `registrationType` = 'RESTRICTED';

ALTER TABLE `RegistrationWorkspace` MODIFY `registrationType` ENUM('INTERNAL_NORMAL', 'RESTRICTED_INTERNAL', 'EXTERNAL') NOT NULL DEFAULT 'INTERNAL_NORMAL';
ALTER TABLE `StudentExamRegistration` MODIFY `registrationType` ENUM('INTERNAL_NORMAL', 'RESTRICTED_INTERNAL', 'EXTERNAL') NOT NULL DEFAULT 'INTERNAL_NORMAL';

-- BillingScope enum migration
ALTER TABLE `RegistrationWorkspace` MODIFY `billingScope` ENUM('NORMAL_BILLING', 'OFFICE_ONLY_BILLING', 'NO_BILLING', 'MANUAL_REVIEW', 'RESTRICTED_BILLING', 'EXTERNAL_BILLING') NOT NULL DEFAULT 'NORMAL_BILLING';
ALTER TABLE `StudentExamRegistration` MODIFY `billingScope` ENUM('NORMAL_BILLING', 'OFFICE_ONLY_BILLING', 'NO_BILLING', 'MANUAL_REVIEW', 'RESTRICTED_BILLING', 'EXTERNAL_BILLING') NOT NULL DEFAULT 'NORMAL_BILLING';

UPDATE `RegistrationWorkspace` SET `billingScope` = 'RESTRICTED_BILLING' WHERE `billingScope` = 'OFFICE_ONLY_BILLING';
UPDATE `StudentExamRegistration` SET `billingScope` = 'RESTRICTED_BILLING' WHERE `billingScope` = 'OFFICE_ONLY_BILLING';
UPDATE `RegistrationWorkspace` SET `billingScope` = 'RESTRICTED_BILLING' WHERE `registrationType` = 'RESTRICTED_INTERNAL' AND `billingScope` = 'MANUAL_REVIEW';
UPDATE `RegistrationWorkspace` SET `billingScope` = 'EXTERNAL_BILLING' WHERE `registrationType` = 'EXTERNAL' AND `billingScope` = 'MANUAL_REVIEW';
UPDATE `StudentExamRegistration` SET `billingScope` = 'RESTRICTED_BILLING' WHERE `registrationType` = 'RESTRICTED_INTERNAL' AND `billingScope` = 'MANUAL_REVIEW';
UPDATE `StudentExamRegistration` SET `billingScope` = 'EXTERNAL_BILLING' WHERE `registrationType` = 'EXTERNAL' AND `billingScope` = 'MANUAL_REVIEW';

ALTER TABLE `RegistrationWorkspace` MODIFY `billingScope` ENUM('NORMAL_BILLING', 'RESTRICTED_BILLING', 'EXTERNAL_BILLING', 'NO_BILLING', 'MANUAL_REVIEW') NOT NULL DEFAULT 'NORMAL_BILLING';
ALTER TABLE `StudentExamRegistration` MODIFY `billingScope` ENUM('NORMAL_BILLING', 'RESTRICTED_BILLING', 'EXTERNAL_BILLING', 'NO_BILLING', 'MANUAL_REVIEW') NOT NULL DEFAULT 'NORMAL_BILLING';

-- Registration audit actions
ALTER TABLE `RegistrationAuditLog` MODIFY `action` ENUM(
  'ADD', 'REMOVE', 'SUBMIT', 'UPDATE', 'CANCEL', 'LOCK', 'ADMIN_ADJUST',
  'STUDENT_ADD', 'STUDENT_REMOVE', 'STUDENT_SUBMIT', 'SYSTEM_LOCK',
  'EO_ADD_AFTER_LOCK', 'EO_REMOVE_AFTER_LOCK', 'EO_REPLACE_AFTER_LOCK',
  'ADMIN_ADD_AFTER_LOCK', 'ADMIN_REMOVE_AFTER_LOCK', 'ADMIN_REPLACE_AFTER_LOCK',
  'TEACHER_CHANGE_REQUEST', 'TEACHER_REQUEST_APPROVED', 'TEACHER_REQUEST_REJECTED',
  'TEACHER_LATE_REGISTRATION_REQUEST', 'TEACHER_LATE_REGISTRATION_APPROVED', 'TEACHER_LATE_REGISTRATION_REJECTED',
  'EO_LATE_REGISTRATION_CREATED', 'ADMIN_LATE_REGISTRATION_CREATED',
  'EO_ASSISTED_REGISTRATION_CREATED', 'ADMIN_ASSISTED_REGISTRATION_CREATED',
  'INTERNAL_NORMAL_REGISTRATION_CREATED', 'RESTRICTED_INTERNAL_REGISTRATION_CREATED', 'EXTERNAL_REGISTRATION_CREATED',
  'INTERNAL_NORMAL_REGISTRATION_UPDATED', 'RESTRICTED_INTERNAL_REGISTRATION_UPDATED', 'EXTERNAL_REGISTRATION_UPDATED',
  'EO_OFFICE_ONLY_REGISTRATION_CREATED', 'ADMIN_OFFICE_ONLY_REGISTRATION_CREATED',
  'EO_RESTRICTED_REGISTRATION_CREATED', 'ADMIN_RESTRICTED_REGISTRATION_CREATED',
  'RESTRICTED_REGISTRATION_UPDATED', 'RESTRICTED_REGISTRATION_CANCELLED',
  'EO_POST_LOCK_ADJUSTMENT', 'ADMIN_POST_LOCK_ADJUSTMENT',
  'STUDENT_REGISTRATION_SUBMITTED', 'EXTERNAL_CANDIDATE_REGISTRATION_CREATED',
  'REGISTRATION_STAGE_CREATED', 'REGISTRATION_STAGE_UPDATED', 'REGISTRATION_STAGE_DISABLED',
  'FEE_STAGE_CREATED', 'FEE_STAGE_UPDATED',
  'STUDENT_REGISTRATION_OPENED', 'STUDENT_REGISTRATION_CLOSED', 'REGISTRATION_WINDOW_CLOSED',
  'ENTRY_TYPE_AUTO_ASSIGNED', 'ENTRY_TYPE_OVERRIDDEN', 'ENTRY_TYPE_DEFAULTED_TO_NORMAL',
  'POST_STUDENT_CLOSE_ADJUSTMENT', 'POST_WINDOW_CLOSE_OVERRIDE',
  'CANDIDATE_REGISTRATION_FEE_ADDED', 'CANDIDATE_REGISTRATION_FEE_REMOVED'
) NOT NULL;

UPDATE `FeeStatement` SET `studentVisible` = false WHERE `statementKind` IN ('RESTRICTED', 'EXTERNAL');
